--------------------------------------------------------
--  DDL for Table TABLEADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TABLEADDRESS" 
   (	"USERID" NUMBER, 
	"PROVINCEID" NUMBER, 
	"KHETID" NUMBER, 
	"KHWANGID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLEKHET
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TABLEKHET" 
   (	"KHETID" NUMBER, 
	"PROVINCEID" NUMBER, 
	"KHETNAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLEKHWANG
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TABLEKHWANG" 
   (	"KHWANGID" NUMBER, 
	"PROVINCEID" NUMBER, 
	"KHETID" NUMBER, 
	"KHWANGNAME" VARCHAR2(100 BYTE), 
	"ZIPCODE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLEPROVINCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TABLEPROVINCE" 
   (	"PROVINCEID" NUMBER, 
	"PROVINCENAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLEUSER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TABLEUSER" 
   (	"USERID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(50 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLEKHET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLEKHET_PK" ON "SYSTEM"."TABLEKHET" ("KHETID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLEKHWANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLEKHWANG_PK" ON "SYSTEM"."TABLEKHWANG" ("KHWANGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLEPROVINCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLEPROVINCE_PK" ON "SYSTEM"."TABLEPROVINCE" ("PROVINCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLEUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TABLEUSER_PK" ON "SYSTEM"."TABLEUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TABLEKHET_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TABLEKHET_TRG" 
BEFORE INSERT ON TABLEKHET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.KHETID IS NULL THEN
      SELECT TABLEKHET_SEQ.NEXTVAL INTO :NEW.KHETID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."TABLEKHET_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLEKHWANG_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TABLEKHWANG_TRG" 
BEFORE INSERT ON TABLEKHWANG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."TABLEKHWANG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLEPROVINCE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TABLEPROVINCE_TRG" 
BEFORE INSERT ON TABLEPROVINCE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROVINCEID IS NULL THEN
      SELECT TABLEPROVINCE_SEQ.NEXTVAL INTO :NEW.PROVINCEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."TABLEPROVINCE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLEKHET
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TABLEKHET" MODIFY ("KHETID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TABLEKHET" ADD CONSTRAINT "TABLEKHET_PK" PRIMARY KEY ("KHETID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLEKHWANG
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TABLEKHWANG" MODIFY ("KHWANGID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TABLEKHWANG" ADD CONSTRAINT "TABLEKHWANG_PK" PRIMARY KEY ("KHWANGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLEPROVINCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TABLEPROVINCE" MODIFY ("PROVINCEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TABLEPROVINCE" ADD CONSTRAINT "TABLEPROVINCE_PK" PRIMARY KEY ("PROVINCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLEUSER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TABLEUSER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TABLEUSER" ADD CONSTRAINT "TABLEUSER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
